audioclassweekly/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('', include('audios.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

audios/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:class_id>/<int:week_id>', views.details, name='details'),
    path('<int:class_id>/<int:week_id>/listen', views.listen, name='listen'),
    path('<int:class_id>/<int:week_id>/upload', views.upload_form, name='upload'),
]

audios/models.py
from django.db import models
import os

# Create your models here.
class AudioClass(models.Model):
    audio_class_name = models.CharField(max_length=200)

    class Meta:
        verbose_name = 'Audio class'
        verbose_name_plural = 'Audio classes'

    def __str__(self):
        return self.audio_class_name

def path_and_rename(path):
    def wrapper(instance, filename):
        ext = filename.split('.')[-1]
        # get filename
        filename = '{}-{}.{}'.format(instance.audio_class.audio_class_name, instance.week_name, ext)
        # return the whole path to the file
        return os.path.join(path, filename)
    return wrapper

class AudioClassWeek(models.Model):
    audio_class = models.ForeignKey(AudioClass, on_delete=models.CASCADE)
    week_name = models.CharField(max_length=200)
    audio_file = models.FileField(upload_to=path_and_rename('uploads/audios'), default='', blank=True, null=True)
    page_views=models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Audio class week'
        verbose_name_plural = 'Audio class weeks'

    def __str__(self):
        return self.audio_class.audio_class_name + ' ' + self.week_name

audios/forms.py
from django import forms
from .models import AudioClassWeek

class AudioClassWeekUploadForm(forms.ModelForm):
    class Meta:
        model = AudioClassWeek
        fields = ['audio_file'] 

audios/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import AudioClass, AudioClassWeek
from .forms import AudioClassWeekUploadForm

def index(request):
    audio_classes = AudioClass.objects.all().order_by('id')
    context = {'audio_classes': audio_classes}
    return render(request, 'audios/index.html', context)

def details(request, class_id, week_id):
    week = AudioClassWeek.objects.get(pk=week_id)
    response = None
    if week.audio_file:
        response = HttpResponseRedirect('/' + str(class_id) + '/' + str(week_id) + '/listen')
    else:
        response = HttpResponseRedirect('/' + str(class_id) + '/' + str(week_id) + '/upload')
    return response

def listen(request, class_id, week_id):
    week = AudioClassWeek.objects.get(pk=week_id)
    if week.audio_file:
        week.page_views = week.page_views + 1
        week.save(update_fields=["page_views"])
        audio_class = AudioClass.objects.get(pk=class_id)
        context = { 'audio_class': audio_class, 'week': week}
        return render(request, 'audios/listen.html', context)
    else:
        return HttpResponseRedirect('/' + str(class_id) + '/' + str(week_id) + '/upload')

def upload_form(request, class_id, week_id):
    exists_week = AudioClassWeek.objects.get(pk=week_id)
    if request.method == 'POST':
        form = AudioClassWeekUploadForm(request.POST, request.FILES, instance=exists_week)
        if form.is_valid():
            form.save()
            return HttpResponse("Uploaded")
    else:
        if exists_week.audio_file:
            return HttpResponseRedirect('/' + str(class_id) + '/' + str(week_id) + '/listen')
        else:
            form = AudioClassWeekUploadForm()
    return render(request, 'audios/upload.html', {'form': form, 'class_id': class_id, 'week_id': week_id, 'week': exists_week})

audios/templates/audios/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BSSM Share Records Trimester3</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelementplayer.min.css" rel="stylesheet"/>
    <link href="{% static 'audios/css/style.css' %}" rel="stylesheet"/>
</head>
<body>
<center>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <p>Contact me: <a href="mailto:ferin.mac@gmail.com?subject=Share Audio Records">ferin.mac@gmail.com</a></p>
    <p>Donate: <a href="http://www.paypal.me/iferinous" target="_blank">paypal.me/iferinous</a></p>
</center>
</body>
</html>

audios/templates/audios/index.html
{% extends "audios/base.html" %}

{% block content %}

{% if audio_classes %}
<br />
<h2>BSSM2 AMTs & Bible Classes Trimester3</h2>
<br />
<table class="center">
  {% for audio_class in audio_classes %}
  <tr>
    <td style="text-align: left;">
      <strong>{{ audio_class.audio_class_name }} </strong>
    </td>
    <td>
      {% for week in audio_class.audioclassweek_set.all %}
      <a href="{% url 'details' audio_class.id week.id %}" {% if not week.audio_file %} style="color:grey;" {% endif %}>
        {{ week.week_name }}
      </a>
      {% endfor %}
    </td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No classes are available.</p>
{% endif %}

<br />
<br />

{% endblock content %}

audios/templates/audios/listen.html
{% extends "audios/base.html" %}
{% load static %}

{% block content %}
<div class="music-player">
  <div class="titre">
    <h3>
      {{ week.audio_class.audio_class_name }}
    </h3>
    <h1>
      {{ week.week_name }}
    </h1>
  </div>
  <div class="lecteur">
    <audio class="fc-media" style="width: 100%;">
      <source src="{{week.audio_file.url}}" />
    </audio>
  </div>
  <div class="downloadfile">
    <a href="{{ week.audio_file.url }}" download><i class="fa fa-download" aria-hidden="true"></i> Download</a>
    ({{ week.page_views }})
  </div>
</div>
<br />
<br />
<p><a href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a></p>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.7/mediaelement-and-player.min.js">
</script>
<script src="{% static 'audios/js/script.js' %}"></script>

{% endblock content %}

audios/templates/audios/upload.html
{% extends "audios/base.html" %}
{% load static %}
{% block content %}
<div id="alert_box"></div>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="music-player">
  <br /><br />
  <h3>
    Upload - {{ week.audio_class.audio_class_name }}
  </h3>
  <h1>
    {{ week.week_name }}
  </h1>
  <br />
  <form enctype="multipart/form-data" onsubmit="onFormSubmit(event)">
    {% csrf_token %}
    <div class="container">
      <div class="row form-group" id="form_div">
        <div class="col-lg-12">
          <label>Select File : </label>
          {{ form.audio_file.errors }}
          {{ form.audio_file }}
        </div>
      </div>
      <br />
      <div class="row form-group" id="submit_div">
        <div class="col-lg-12">
          <button type="submit" value="Upload" class="btn btn-success">SUBMIT</button>
        </div>
      </div>
      <div class="form-group" style="display:none;" id="progress_div">
        <div class="progress">
          <div class="progress-bar" id="progress_bar" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">0%</div>
        </div>
      </div>
      <div class="form-group">
        <p style="color:white;" id="progress_text"></p>
      </div>
    </div>
  </form>
</div>
<br />
<br />
<p><a href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a></p>

</script>
<script src="{% static 'audios/js/script.js' %}"></script>

<script>
  var csrf = document.getElementsByName('csrfmiddlewaretoken')
  var input = document.getElementById('id_audio_file')

  function onFormSubmit(event) {
    event.preventDefault();

    //if file selected
    if (input.files.length != 0) {
      document.getElementById("alert_box").style["display"] = "none";
      var file_data = input.files[0]
      console.log(file_data)
      var formData = new FormData();
      formData.append('csrfmiddlewaretoken', csrf[0].value)
      formData.append("audio_file", file_data);

      var xhr = new XMLHttpRequest();
      xhr.open("POST", "{% url 'upload' class_id week_id %}");
      xhr.onreadystatechange = function() {
        // In local files, status is 0 upon success in Mozilla Firefox
        if (xhr.readyState === XMLHttpRequest.DONE) {
          var status = xhr.status;
          if ((status === 0 || (status >= 200 && status < 400)) && (xhr.responseText.trim() == 'Uploaded')) {
            // The request has been completed successfully, redirect to listen page
            window.location.href = 'listen';
          } else {
            // Oh no! There has been an error with the request!
            document.getElementById("alert_box").innerHTML = `<div class="alert alert-danger" role="alert">
                                      Oops... something went wrong
                                  </div>`;
          }
        }
      };
      xhr.upload.addEventListener("progress", function(ev) {
        if (ev.lengthComputable) {
          var percentage = (ev.loaded / ev.total * 100 | 0);
          document.getElementById("form_div").style["display"] = "none";
          document.getElementById("submit_div").style["display"] = "none";
          document.getElementById("progress_div").style["display"] = "block";
          document.getElementById("progress_bar").style["width"] = "" + percentage + "%";
          document.getElementById("progress_bar").innerHTML = "" + percentage + "%";
          document.getElementById("progress_text").innerHTML = "Uploaded : " + parseInt(ev.loaded / 1000000) + "/" + parseInt(ev.total / 1000000) + " MB";
          console.log("Uploaded : " + ev.loaded);
          console.log("TOTAL : " + ev.total);
          console.log(percentage)
        }
      });
      xhr.send(formData);
    } else {
      document.getElementById("alert_box").innerHTML = `<div class="alert alert-danger" role="alert">
                                Please select your file.
                            </div>`;
    }

  }
  input.accept = "audio/*, .mp3, .mp4, .m4a, .m4v";
</script>
{% endblock content %}